/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/status-tag"

// Components
export * from './status-tag.component';

// Enums
export * from './enums/status-tag-styles.enum';
export * from './enums/status-tag-type.enum';

// Configs
export * from './models/status-tag.config';

// TODO: Rename files
export * from './enums/enum-status-tag';
