/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "projects/api-layer/src/lib/contacts"

// Services
export * from './services/contacts.service';

// Commands
export * from './models/requests/add-contact.command';
export * from './models/requests/update-contact.command';

// Dtos
export * from './models/dtos/contacts/contacts-billing-info.dto';
export * from './models/dtos/contacts/contacts-contact.dto';
export * from './models/dtos/contacts/contacts-person-address.dto';
export * from './models/dtos/contacts/contacts-person-communication-channel.dto';
export * from './models/dtos/contacts/contacts-person-document.dto';
export * from './models/dtos/contacts/contacts-person-info.dto';
export * from './models/dtos/contacts/contacts-person-name.dto';
export * from './models/dtos/contacts/contacts-person.dto';

// Enums
export * from './models/dtos/enums/contacts-communication-channel-scope.enum';
export * from './models/dtos/enums/contacts-contact-type.enum';
