//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export class AddContactCommand {
    authenticationToken?: string | undefined;
    journeysIds?: string[] | undefined;
    contacts?: Contact[] | undefined;

    init(_data?: any) {
        if (_data) {
            this.authenticationToken = _data["authenticationToken"];
            if (Array.isArray(_data["journeysIds"])) {
                this.journeysIds = [] as any;
                for (let item of _data["journeysIds"])
                    this.journeysIds!.push(item);
            }
            if (Array.isArray(_data["contacts"])) {
                this.contacts = [] as any;
                for (let item of _data["contacts"])
                    this.contacts!.push(Contact.fromJS(item));
            }
        }
    }

    static fromJS(data: any): AddContactCommand {
        data = typeof data === 'object' ? data : {};
        let result = new AddContactCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["authenticationToken"] = this.authenticationToken;
        if (Array.isArray(this.journeysIds)) {
            data["journeysIds"] = [];
            for (let item of this.journeysIds)
                data["journeysIds"].push(item);
        }
        if (Array.isArray(this.contacts)) {
            data["contacts"] = [];
            for (let item of this.contacts)
                data["contacts"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export class BillingInfo {
    companyName?: string | undefined;
    vatNumber?: string | undefined;
    name?: string | undefined;
    nationalID?: string | undefined;
    taxOffice?: string | undefined;
    usage?: string | undefined;

    init(_data?: any) {
        if (_data) {
            this.companyName = _data["companyName"];
            this.vatNumber = _data["vatNumber"];
            this.name = _data["name"];
            this.nationalID = _data["nationalID"];
            this.taxOffice = _data["taxOffice"];
            this.usage = _data["usage"];
        }
    }

    static fromJS(data: any): BillingInfo {
        data = typeof data === 'object' ? data : {};
        let result = new BillingInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["companyName"] = this.companyName;
        data["vatNumber"] = this.vatNumber;
        data["name"] = this.name;
        data["nationalID"] = this.nationalID;
        data["taxOffice"] = this.taxOffice;
        data["usage"] = this.usage;
        return data;
    }
}

export enum ChannelScopeType {
    Default = "Default",
    Personal = "Personal",
    Business = "Business",
    Other = "Other",
}

export enum ChannelType {
    Email = "Email",
    SMS = "SMS",
    Phone = "Phone",
}

export class Contact {
    name?: PersonName;
    address?: PersonAddress;
    documents?: PersonDocument[] | undefined;
    personInfo?: PersonInfo;
    channels?: PersonCommunicationChannel[] | undefined;
    type?: ContactType;
    billingInfo?: BillingInfo;
    mktOption?: boolean;
    readonly id?: string | undefined;
    referenceId?: string | undefined;
    paxReferenceId?: string | undefined;
    relationship?: string | undefined;
    refuseContact?: boolean;

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"] ? PersonName.fromJS(_data["name"]) : undefined as any;
            this.address = _data["address"] ? PersonAddress.fromJS(_data["address"]) : undefined as any;
            if (Array.isArray(_data["documents"])) {
                this.documents = [] as any;
                for (let item of _data["documents"])
                    this.documents!.push(PersonDocument.fromJS(item));
            }
            this.personInfo = _data["personInfo"] ? PersonInfo.fromJS(_data["personInfo"]) : undefined as any;
            if (Array.isArray(_data["channels"])) {
                this.channels = [] as any;
                for (let item of _data["channels"])
                    this.channels!.push(PersonCommunicationChannel.fromJS(item));
            }
            this.type = _data["type"];
            this.billingInfo = _data["billingInfo"] ? BillingInfo.fromJS(_data["billingInfo"]) : undefined as any;
            this.mktOption = _data["mktOption"];
            (this as any).id = _data["id"];
            this.referenceId = _data["referenceId"];
            this.paxReferenceId = _data["paxReferenceId"];
            this.relationship = _data["relationship"];
            this.refuseContact = _data["refuseContact"];
        }
    }

    static fromJS(data: any): Contact {
        data = typeof data === 'object' ? data : {};
        let result = new Contact();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name ? this.name.toJSON() : undefined as any;
        data["address"] = this.address ? this.address.toJSON() : undefined as any;
        if (Array.isArray(this.documents)) {
            data["documents"] = [];
            for (let item of this.documents)
                data["documents"].push(item ? item.toJSON() : undefined as any);
        }
        data["personInfo"] = this.personInfo ? this.personInfo.toJSON() : undefined as any;
        if (Array.isArray(this.channels)) {
            data["channels"] = [];
            for (let item of this.channels)
                data["channels"].push(item ? item.toJSON() : undefined as any);
        }
        data["type"] = this.type;
        data["billingInfo"] = this.billingInfo ? this.billingInfo.toJSON() : undefined as any;
        data["mktOption"] = this.mktOption;
        data["id"] = this.id;
        data["referenceId"] = this.referenceId;
        data["paxReferenceId"] = this.paxReferenceId;
        data["relationship"] = this.relationship;
        data["refuseContact"] = this.refuseContact;
        return data;
    }
}

export enum ContactType {
    Booking = "Booking",
    Emergency = "Emergency",
    Billing = "Billing",
    Other = "Other",
}

export enum DocumentType {
    P = "P",
    NI = "NI",
    ID = "ID",
    M = "M",
    U = "U",
    V = "V",
    A = "A",
    K = "K",
    R = "R",
    Z = "Z",
    B = "B",
    D = "D",
    I = "I",
    N = "N",
    DL = "DL",
    NYSC = "NYSC",
    SID = "SID",
    NIN = "NIN",
    PVC = "PVC",
    WID = "WID",
}

export enum GenderType {
    Unknown = "Unknown",
    Male = "Male",
    Female = "Female",
    Unspecified = "Unspecified",
}

export class PersonAddress {
    country?: string | undefined;
    province?: string | undefined;
    city?: string | undefined;
    zipCode?: string | undefined;
    addressLine?: string | undefined;
    addressLine2?: string | undefined;

    init(_data?: any) {
        if (_data) {
            this.country = _data["country"];
            this.province = _data["province"];
            this.city = _data["city"];
            this.zipCode = _data["zipCode"];
            this.addressLine = _data["addressLine"];
            this.addressLine2 = _data["addressLine2"];
        }
    }

    static fromJS(data: any): PersonAddress {
        data = typeof data === 'object' ? data : {};
        let result = new PersonAddress();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["country"] = this.country;
        data["province"] = this.province;
        data["city"] = this.city;
        data["zipCode"] = this.zipCode;
        data["addressLine"] = this.addressLine;
        data["addressLine2"] = this.addressLine2;
        return data;
    }
}

export class PersonCommunicationChannel {
    type?: ChannelType;
    scope?: ChannelScopeType;
    info?: string | undefined;
    prefix?: string | undefined;
    cultureCode?: string | undefined;
    additionalData?: string | undefined;

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.scope = _data["scope"];
            this.info = _data["info"];
            this.prefix = _data["prefix"];
            this.cultureCode = _data["cultureCode"];
            this.additionalData = _data["additionalData"];
        }
    }

    static fromJS(data: any): PersonCommunicationChannel {
        data = typeof data === 'object' ? data : {};
        let result = new PersonCommunicationChannel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["scope"] = this.scope;
        data["info"] = this.info;
        data["prefix"] = this.prefix;
        data["cultureCode"] = this.cultureCode;
        data["additionalData"] = this.additionalData;
        return data;
    }
}

export class PersonDocument {
    type?: DocumentType;
    number?: string | undefined;
    issuedCountry?: string | undefined;
    nationality?: string | undefined;
    expirationDate?: Date;
    issuedDate?: Date;
    isDefault?: boolean;

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.number = _data["number"];
            this.issuedCountry = _data["issuedCountry"];
            this.nationality = _data["nationality"];
            this.expirationDate = _data["expirationDate"] ? new Date(_data["expirationDate"].toString()) : undefined as any;
            this.issuedDate = _data["issuedDate"] ? new Date(_data["issuedDate"].toString()) : undefined as any;
            this.isDefault = _data["isDefault"];
        }
    }

    static fromJS(data: any): PersonDocument {
        data = typeof data === 'object' ? data : {};
        let result = new PersonDocument();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["number"] = this.number;
        data["issuedCountry"] = this.issuedCountry;
        data["nationality"] = this.nationality;
        data["expirationDate"] = this.expirationDate ? this.expirationDate.toISOString() : undefined as any;
        data["issuedDate"] = this.issuedDate ? this.issuedDate.toISOString() : undefined as any;
        data["isDefault"] = this.isDefault;
        return data;
    }
}

export class PersonInfo {
    gender?: GenderType;
    weight?: WeightType;
    dateOfBirth?: Date;
    nationality?: string | undefined;

    init(_data?: any) {
        if (_data) {
            this.gender = _data["gender"];
            this.weight = _data["weight"];
            this.dateOfBirth = _data["dateOfBirth"] ? new Date(_data["dateOfBirth"].toString()) : undefined as any;
            this.nationality = _data["nationality"];
        }
    }

    static fromJS(data: any): PersonInfo {
        data = typeof data === 'object' ? data : {};
        let result = new PersonInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["gender"] = this.gender;
        data["weight"] = this.weight;
        data["dateOfBirth"] = this.dateOfBirth ? this.dateOfBirth.toISOString() : undefined as any;
        data["nationality"] = this.nationality;
        return data;
    }
}

export class PersonName {
    title?: string | undefined;
    first?: string | undefined;
    middle?: string | undefined;
    last?: string | undefined;
    suffix?: string | undefined;

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            this.first = _data["first"];
            this.middle = _data["middle"];
            this.last = _data["last"];
            this.suffix = _data["suffix"];
        }
    }

    static fromJS(data: any): PersonName {
        data = typeof data === 'object' ? data : {};
        let result = new PersonName();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["first"] = this.first;
        data["middle"] = this.middle;
        data["last"] = this.last;
        data["suffix"] = this.suffix;
        return data;
    }
}

export class UpdateContactCommand {
    authenticationToken?: string | undefined;
    journeysIds?: string[] | undefined;
    contacts?: { [key: string]: Contact; } | undefined;

    init(_data?: any) {
        if (_data) {
            this.authenticationToken = _data["authenticationToken"];
            if (Array.isArray(_data["journeysIds"])) {
                this.journeysIds = [] as any;
                for (let item of _data["journeysIds"])
                    this.journeysIds!.push(item);
            }
            if (_data["contacts"]) {
                this.contacts = {} as any;
                for (let key in _data["contacts"]) {
                    if (_data["contacts"].hasOwnProperty(key))
                        (this.contacts as any)![key] = _data["contacts"][key] ? Contact.fromJS(_data["contacts"][key]) : new Contact();
                }
            }
        }
    }

    static fromJS(data: any): UpdateContactCommand {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateContactCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["authenticationToken"] = this.authenticationToken;
        if (Array.isArray(this.journeysIds)) {
            data["journeysIds"] = [];
            for (let item of this.journeysIds)
                data["journeysIds"].push(item);
        }
        if (this.contacts) {
            data["contacts"] = {};
            for (let key in this.contacts) {
                if (this.contacts.hasOwnProperty(key))
                    (data["contacts"] as any)[key] = this.contacts[key] ? this.contacts[key].toJSON() : undefined as any;
            }
        }
        return data;
    }
}

export enum WeightType {
    Unknown = "Unknown",
    Male = "Male",
    Female = "Female",
    Child = "Child",
    Infant = "Infant",
}