//----------------------
// <auto-generated>
//     Generated barrel export for contacts models
//     Custom aliases are preserved across regenerations
// </auto-generated>
//----------------------

export { AddContactCommand } from './contacts-models';
export { BillingInfo } from './contacts-models';
export { ChannelScopeType } from './contacts-models';
export { ChannelType } from './contacts-models';
export { Contact } from './contacts-models';
export { ContactType } from './contacts-models';
export { DocumentType } from './contacts-models';
export { GenderType } from './contacts-models';
export { PersonAddress } from './contacts-models';
export { PersonCommunicationChannel } from './contacts-models';
export { PersonDocument } from './contacts-models';
export { PersonInfo } from './contacts-models';
export { PersonName } from './contacts-models';
export { UpdateContactCommand } from './contacts-models';
export { WeightType } from './contacts-models';

// Export all models for client
export * from './contacts-models';
