/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/carousel"

// Components
export * from './carousel.component';

// Directives
export * from './directives/carousel-item.directive';

// Configs
export * from './models/carousel.config';
