/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/avatar"

// Components
export * from './avatar.component';

// Enums
export * from './enums/avatar-size.enum';

// Configs
export * from './models/avatar.config';

// Tokens
export * from './tokens/avatar-default-config.token';
