//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { AccountDto, AccountSettingsDto, AccountStatus, AccountSubscriptionDto, AgencyInfoDto, Assembly, BalanceDto, BillingInfoDto, CallingConventions, ChannelScopeType, ChannelType, CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null, ConstructorInfo, ContactDto, ContactType, CustomAttributeData, CustomAttributeNamedArgument, CustomAttributeTypedArgument, CustomerProgramDto, DocumentType, EliteProgressDto, Error as ApiError, EventAttributes, EventInfo, Exception, ExceptionInfoType, FieldAttributes, FieldInfo, FrequentTravelerDto, GenderType, GenericParameterAttributes, ICustomAttributeProvider, IntPtr, LayoutKind, LifemilesDto, MemberInfo, MembershipDto, MemberTypes, MethodAttributes, MethodBase, MethodImplAttributes, MethodInfo, Module, ModuleHandle, OrganizationInfoDto, ParameterAttributes, ParameterInfo, PaymentFrequency, PersonAddressDto, PersonCommunicationChannelDto, PersonDocumentDto, PersonInfoDto, PersonNameDto, PriceDto, PrivacySettings, PropertyAttributes, PropertyInfo, QualifyingMilesDto, QueryResponse_1OfOfAccountDtoAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null, ResponseObject_1OfOfAccountDtoAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null, ResponseObject_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null, RuntimeFieldHandle, RuntimeMethodHandle, RuntimeTypeHandle, SecurityRuleSet, ServiceSettingsDto, StructLayoutAttribute, Type, TypeAttributes, TypeInfo, UpdateAccountPrivacySettingsCommand, UpdateAccountPrivacySettingsRequest, UpdateCurrentAccountCommand, UpdateCurrentAccountRequest, UpdateTravelDocumentCommand, UpdateTravelDocumentsRequest, VoidCommandResponse, WeightType } from './models/accountV2';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

export interface IAccountV2Client {
    /**
     * @param body (optional) 
     * @return OK
     */
    travelDocuments(version: string, body?: UpdateTravelDocumentCommand | undefined): Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
    /**
     * @param body (optional) 
     * @return OK
     */
    privacySettings(version: string, body?: UpdateAccountPrivacySettingsCommand | undefined): Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
    /**
     * @param isCancellationRequested (optional) 
     * @param canBeCanceled (optional) 
     * @param waitHandle_Handle (optional) 
     * @param waitHandle_SafeWaitHandle_IsInvalid (optional) 
     * @param waitHandle_SafeWaitHandle_IsClosed (optional) 
     * @param forceRefresh (optional) 
     * @return OK
     */
    sessionGET(version: string, isCancellationRequested?: boolean | undefined, canBeCanceled?: boolean | undefined, waitHandle_Handle?: IntPtr | undefined, waitHandle_SafeWaitHandle_IsInvalid?: boolean | undefined, waitHandle_SafeWaitHandle_IsClosed?: boolean | undefined, forceRefresh?: boolean | undefined): Observable<QueryResponse_1OfOfAccountDtoAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
    /**
     * @param body (optional) 
     * @return OK
     */
    sessionPATCH(version: string, body?: UpdateCurrentAccountCommand | undefined): Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
}

@Injectable()
export class AccountV2Client implements IAccountV2Client {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "/accounts";
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    travelDocuments(version: string = '2', body?: UpdateTravelDocumentCommand | undefined): Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null> {
        let url_ = this.baseUrl + "/api/v{version}/account/travelDocuments";
        if (version === undefined || version === null)
            throw new globalThis.Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json-patch+json",
                "Accept": "application/json"
            })
        };

        return this.http.request("patch", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processTravelDocuments(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processTravelDocuments(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
        }));
    }

    protected processTravelDocuments(response: HttpResponseBase): Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    privacySettings(version: string = '2', body?: UpdateAccountPrivacySettingsCommand | undefined): Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null> {
        let url_ = this.baseUrl + "/api/v{version}/account/privacySettings";
        if (version === undefined || version === null)
            throw new globalThis.Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json-patch+json",
                "Accept": "application/json"
            })
        };

        return this.http.request("patch", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processPrivacySettings(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processPrivacySettings(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
        }));
    }

    protected processPrivacySettings(response: HttpResponseBase): Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param isCancellationRequested (optional) 
     * @param canBeCanceled (optional) 
     * @param waitHandle_Handle (optional) 
     * @param waitHandle_SafeWaitHandle_IsInvalid (optional) 
     * @param waitHandle_SafeWaitHandle_IsClosed (optional) 
     * @param forceRefresh (optional) 
     * @return OK
     */
    sessionGET(version: string = '2', isCancellationRequested?: boolean | undefined, canBeCanceled?: boolean | undefined, waitHandle_Handle?: IntPtr | undefined, waitHandle_SafeWaitHandle_IsInvalid?: boolean | undefined, waitHandle_SafeWaitHandle_IsClosed?: boolean | undefined, forceRefresh?: boolean | undefined): Observable<QueryResponse_1OfOfAccountDtoAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null> {
        let url_ = this.baseUrl + "/api/v{version}/session?";
        if (version === undefined || version === null)
            throw new globalThis.Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        if (isCancellationRequested === null)
            throw new globalThis.Error("The parameter 'isCancellationRequested' cannot be null.");
        else if (isCancellationRequested !== undefined)
            url_ += "IsCancellationRequested=" + encodeURIComponent("" + isCancellationRequested) + "&";
        if (canBeCanceled === null)
            throw new globalThis.Error("The parameter 'canBeCanceled' cannot be null.");
        else if (canBeCanceled !== undefined)
            url_ += "CanBeCanceled=" + encodeURIComponent("" + canBeCanceled) + "&";
        if (waitHandle_Handle === null)
            throw new globalThis.Error("The parameter 'waitHandle_Handle' cannot be null.");
        else if (waitHandle_Handle !== undefined)
            url_ += "WaitHandle.Handle=" + encodeURIComponent("" + waitHandle_Handle) + "&";
        if (waitHandle_SafeWaitHandle_IsInvalid === null)
            throw new globalThis.Error("The parameter 'waitHandle_SafeWaitHandle_IsInvalid' cannot be null.");
        else if (waitHandle_SafeWaitHandle_IsInvalid !== undefined)
            url_ += "WaitHandle.SafeWaitHandle.IsInvalid=" + encodeURIComponent("" + waitHandle_SafeWaitHandle_IsInvalid) + "&";
        if (waitHandle_SafeWaitHandle_IsClosed === null)
            throw new globalThis.Error("The parameter 'waitHandle_SafeWaitHandle_IsClosed' cannot be null.");
        else if (waitHandle_SafeWaitHandle_IsClosed !== undefined)
            url_ += "WaitHandle.SafeWaitHandle.IsClosed=" + encodeURIComponent("" + waitHandle_SafeWaitHandle_IsClosed) + "&";
        if (forceRefresh === null)
            throw new globalThis.Error("The parameter 'forceRefresh' cannot be null.");
        else if (forceRefresh !== undefined)
            url_ += "forceRefresh=" + encodeURIComponent("" + forceRefresh) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSessionGET(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSessionGET(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<QueryResponse_1OfOfAccountDtoAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
                }
            } else
                return _observableThrow(response_) as any as Observable<QueryResponse_1OfOfAccountDtoAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
        }));
    }

    protected processSessionGET(response: HttpResponseBase): Observable<QueryResponse_1OfOfAccountDtoAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = QueryResponse_1OfOfAccountDtoAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    sessionPATCH(version: string = '2', body?: UpdateCurrentAccountCommand | undefined): Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null> {
        let url_ = this.baseUrl + "/api/v{version}/session";
        if (version === undefined || version === null)
            throw new globalThis.Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json-patch+json",
                "Accept": "application/json"
            })
        };

        return this.http.request("patch", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSessionPATCH(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSessionPATCH(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
        }));
    }

    protected processSessionPATCH(response: HttpResponseBase): Observable<CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CommandResponse_1OfOfVoidCommandResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    return _observableThrow(new ApiException(message, status, response, headers, result));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}