//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { AccountSubscription, Assembly, CallingConventions, ConstructorInfo, Currency, CustomAttributeData, CustomAttributeNamedArgument, CustomAttributeTypedArgument, Error as ApiError, EventAttributes, EventInfo, Exception, ExceptionInfoType, FieldAttributes, FieldInfo, GenericParameterAttributes, ICustomAttributeProvider, IntPtr, LayoutKind, Location, MemberInfo, MemberTypes, MethodAttributes, MethodBase, MethodImplAttributes, MethodInfo, Module, ModuleHandle, ParameterAttributes, ParameterInfo, PropertyAttributes, PropertyInfo, QueryResponse_1OfOfLocationAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null, QueryResponse_1OfOfSessionSettingsResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null, ResponseObject_1OfOfLocationAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null, ResponseObject_1OfOfSessionSettingsResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null, RuntimeFieldHandle, RuntimeMethodHandle, RuntimeTypeHandle, Search, SecurityRuleSet, SessionSettingsResponse, StructLayoutAttribute, Type, TypeAttributes, TypeInfo } from './models/location';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

export interface ILocationClient {
    /**
     * @param position_Latitude (optional) 
     * @param position_Longitude (optional) 
     * @param culture (optional) 
     * @param isLoggedIn (optional) 
     * @param authenticationToken (optional) 
     * @return OK
     */
    location(version: string, position_Latitude?: string | undefined, position_Longitude?: string | undefined, culture?: string | undefined, isLoggedIn?: boolean | undefined, authenticationToken?: string | undefined): Observable<QueryResponse_1OfOfLocationAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
    /**
     * @param latitude (optional) 
     * @param longitude (optional) 
     * @param culture (optional) 
     * @param isLoggedIn (optional) 
     * @param authenticationToken (optional) 
     * @return OK
     */
    sessionSettings(version: string, latitude?: string | undefined, longitude?: string | undefined, culture?: string | undefined, isLoggedIn?: boolean | undefined, authenticationToken?: string | undefined): Observable<QueryResponse_1OfOfSessionSettingsResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
}

@Injectable()
export class LocationClient implements ILocationClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "/location";
    }

    /**
     * @param position_Latitude (optional) 
     * @param position_Longitude (optional) 
     * @param culture (optional) 
     * @param isLoggedIn (optional) 
     * @param authenticationToken (optional) 
     * @return OK
     */
    location(version: string = '1', position_Latitude?: string | undefined, position_Longitude?: string | undefined, culture?: string | undefined, isLoggedIn?: boolean | undefined, authenticationToken?: string | undefined): Observable<QueryResponse_1OfOfLocationAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null> {
        let url_ = this.baseUrl + "/api/v{version}/location?";
        if (version === undefined || version === null)
            throw new globalThis.Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        if (position_Latitude === null)
            throw new globalThis.Error("The parameter 'position_Latitude' cannot be null.");
        else if (position_Latitude !== undefined)
            url_ += "Position.Latitude=" + encodeURIComponent("" + position_Latitude) + "&";
        if (position_Longitude === null)
            throw new globalThis.Error("The parameter 'position_Longitude' cannot be null.");
        else if (position_Longitude !== undefined)
            url_ += "Position.Longitude=" + encodeURIComponent("" + position_Longitude) + "&";
        if (culture === null)
            throw new globalThis.Error("The parameter 'culture' cannot be null.");
        else if (culture !== undefined)
            url_ += "Culture=" + encodeURIComponent("" + culture) + "&";
        if (isLoggedIn === null)
            throw new globalThis.Error("The parameter 'isLoggedIn' cannot be null.");
        else if (isLoggedIn !== undefined)
            url_ += "IsLoggedIn=" + encodeURIComponent("" + isLoggedIn) + "&";
        if (authenticationToken === null)
            throw new globalThis.Error("The parameter 'authenticationToken' cannot be null.");
        else if (authenticationToken !== undefined)
            url_ += "AuthenticationToken=" + encodeURIComponent("" + authenticationToken) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processLocation(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processLocation(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<QueryResponse_1OfOfLocationAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
                }
            } else
                return _observableThrow(response_) as any as Observable<QueryResponse_1OfOfLocationAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
        }));
    }

    protected processLocation(response: HttpResponseBase): Observable<QueryResponse_1OfOfLocationAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = QueryResponse_1OfOfLocationAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * @param latitude (optional) 
     * @param longitude (optional) 
     * @param culture (optional) 
     * @param isLoggedIn (optional) 
     * @param authenticationToken (optional) 
     * @return OK
     */
    sessionSettings(version: string = '1', latitude?: string | undefined, longitude?: string | undefined, culture?: string | undefined, isLoggedIn?: boolean | undefined, authenticationToken?: string | undefined): Observable<QueryResponse_1OfOfSessionSettingsResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null> {
        let url_ = this.baseUrl + "/api/v{version}/sessionSettings?";
        if (version === undefined || version === null)
            throw new globalThis.Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        if (latitude === null)
            throw new globalThis.Error("The parameter 'latitude' cannot be null.");
        else if (latitude !== undefined)
            url_ += "Latitude=" + encodeURIComponent("" + latitude) + "&";
        if (longitude === null)
            throw new globalThis.Error("The parameter 'longitude' cannot be null.");
        else if (longitude !== undefined)
            url_ += "Longitude=" + encodeURIComponent("" + longitude) + "&";
        if (culture === null)
            throw new globalThis.Error("The parameter 'culture' cannot be null.");
        else if (culture !== undefined)
            url_ += "Culture=" + encodeURIComponent("" + culture) + "&";
        if (isLoggedIn === null)
            throw new globalThis.Error("The parameter 'isLoggedIn' cannot be null.");
        else if (isLoggedIn !== undefined)
            url_ += "IsLoggedIn=" + encodeURIComponent("" + isLoggedIn) + "&";
        if (authenticationToken === null)
            throw new globalThis.Error("The parameter 'authenticationToken' cannot be null.");
        else if (authenticationToken !== undefined)
            url_ += "AuthenticationToken=" + encodeURIComponent("" + authenticationToken) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSessionSettings(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSessionSettings(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<QueryResponse_1OfOfSessionSettingsResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
                }
            } else
                return _observableThrow(response_) as any as Observable<QueryResponse_1OfOfSessionSettingsResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null>;
        }));
    }

    protected processSessionSettings(response: HttpResponseBase): Observable<QueryResponse_1OfOfSessionSettingsResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = QueryResponse_1OfOfSessionSettingsResponseAndApplicationAnd_0AndCulture_neutralAndPublicKeyToken_null.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    return _observableThrow(new ApiException(message, status, response, headers, result));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}