import { Country } from '@dcx/ui/libs';

export const COUNTRY: Country[] = [
  {
    name: 'Bangladesh',
    code: 'BD',
    currencyCode: 'BDT',
    phonePrefix: '880',
  },
  {
    name: 'Belgium',
    code: 'BE',
    currencyCode: 'EUR',
    phonePrefix: '32',
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    currencyCode: 'XOF',
    phonePrefix: '226',
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    currencyCode: 'BGN',
    phonePrefix: '359',
  },
  {
    name: 'Bosnia & Herzegovina',
    code: 'BA',
    currencyCode: 'BAM',
    phonePrefix: '387',
  },
  {
    name: 'Barbados',
    code: 'BB',
    currencyCode: 'BBD',
    phonePrefix: '+1-246',
  },
  {
    name: 'Wallis & Futuna',
    code: 'WF',
    currencyCode: 'XPF',
    phonePrefix: '681',
  },
  {
    name: 'Saint Barthelemy',
    code: 'BL',
    currencyCode: 'EUR',
    phonePrefix: '590',
  },
  {
    name: 'Bermuda',
    code: 'BM',
    currencyCode: 'BMD',
    phonePrefix: '+1-441',
  },
  {
    name: 'Brunei',
    code: 'BN',
    currencyCode: 'BND',
    phonePrefix: '673',
  },
  {
    name: 'Bolivia',
    code: 'BO',
    currencyCode: 'BOB',
    phonePrefix: '591',
  },
  {
    name: 'Bahrain',
    code: 'BH',
    currencyCode: 'BHD',
    phonePrefix: '973',
  },
  {
    name: 'Burundi',
    code: 'BI',
    currencyCode: 'BIF',
    phonePrefix: '257',
  },
  {
    name: 'Benin',
    code: 'BJ',
    currencyCode: 'XOF',
    phonePrefix: '229',
  },
  {
    name: 'Bhutan',
    code: 'BT',
    currencyCode: 'BTN',
    phonePrefix: '975',
  },
  {
    name: 'Jamaica',
    code: 'JM',
    currencyCode: 'JMD',
    phonePrefix: '+1-876',
  },
  {
    name: 'Botswana',
    code: 'BW',
    currencyCode: 'BWP',
    phonePrefix: '267',
  },
  {
    name: 'Samoa',
    code: 'WS',
    currencyCode: 'WST',
    phonePrefix: '685',
  },
  {
    name: 'Bonaire',
    code: 'BQ',
    currencyCode: 'USD',
    phonePrefix: '599',
  },
  {
    name: 'Brazil',
    code: 'BR',
    currencyCode: 'BRL',
    phonePrefix: '55',
  },
  {
    name: 'Bahamas',
    code: 'BS',
    currencyCode: 'BSD',
    phonePrefix: '+1-242',
  },
  {
    name: 'Jersey',
    code: 'JE',
    currencyCode: 'JEP',
    phonePrefix: '+44-1534',
  },
  {
    name: 'Belarus',
    code: 'BY',
    currencyCode: 'BYN',
    phonePrefix: '375',
  },
  {
    name: 'Belize',
    code: 'BZ',
    currencyCode: 'BZD',
    phonePrefix: '501',
  },
  {
    name: 'Russia',
    code: 'RU',
    currencyCode: 'RUB',
    phonePrefix: '7',
  },
  {
    name: 'Rwanda',
    code: 'RW',
    currencyCode: 'RWF',
    phonePrefix: '250',
  },
  {
    name: 'Serbia',
    code: 'RS',
    currencyCode: 'RSD',
    phonePrefix: '381',
  },
  {
    name: 'Timor-Leste',
    code: 'TL',
    currencyCode: 'USD',
    phonePrefix: '670',
  },
  {
    name: 'Reunion',
    code: 'RE',
    currencyCode: 'EUR',
    phonePrefix: '262',
  },
  {
    name: 'Turkmenistan',
    code: 'TM',
    currencyCode: 'TMT',
    phonePrefix: '993',
  },
  {
    name: 'Tajikistan',
    code: 'TJ',
    currencyCode: 'TJS',
    phonePrefix: '992',
  },
  {
    name: 'Romania',
    code: 'RO',
    currencyCode: 'RON',
    phonePrefix: '40',
  },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    currencyCode: 'XOF',
    phonePrefix: '250',
  },
  {
    name: 'Guam',
    code: 'GU',
    currencyCode: 'USD',
    phonePrefix: '+1-671',
  },
  {
    name: 'Guatemala',
    code: 'GT',
    currencyCode: 'GTQ',
    phonePrefix: '502',
  },
  {
    name: 'Greece',
    code: 'GR',
    currencyCode: 'EUR',
    phonePrefix: '30',
  },
  {
    name: 'Equatorial Guinea',
    code: 'GQ',
    currencyCode: 'XAF',
    phonePrefix: '240',
  },
  {
    name: 'Guadeloupe',
    code: 'GP',
    currencyCode: 'EUR',
    phonePrefix: '590',
  },
  {
    name: 'Japan',
    code: 'JP',
    currencyCode: 'JPY',
    phonePrefix: '81',
  },
  {
    name: 'Guyana',
    code: 'GY',
    currencyCode: 'GYD',
    phonePrefix: '592',
  },
  {
    name: 'Guernsey',
    code: 'GG',
    currencyCode: 'GGP',
    phonePrefix: '+44-1481',
  },
  {
    name: 'French Guiana',
    code: 'GF',
    currencyCode: 'EUR',
    phonePrefix: '594',
  },
  {
    name: 'Georgia',
    code: 'GE',
    currencyCode: 'GEL',
    phonePrefix: '995',
  },
  {
    name: 'Grenada',
    code: 'GD',
    currencyCode: 'XCD',
    phonePrefix: '+1-473',
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    currencyCode: 'GBP',
    phonePrefix: '44',
  },
  {
    name: 'Gabon',
    code: 'GA',
    currencyCode: 'XAF',
    phonePrefix: '241',
  },
  {
    name: 'El Salvador',
    code: 'SV',
    currencyCode: 'USD',
    phonePrefix: '503',
  },
  {
    name: 'Guinea',
    code: 'GN',
    currencyCode: 'GNF',
    phonePrefix: '224',
  },
  {
    name: 'Gambia',
    code: 'GM',
    currencyCode: 'GMD',
    phonePrefix: '220',
  },
  {
    name: 'Greenland',
    code: 'GL',
    currencyCode: 'DKK',
    phonePrefix: '299',
  },
  {
    name: 'Gibraltar',
    code: 'GI',
    currencyCode: 'GIP',
    phonePrefix: '350',
  },
  {
    name: 'Ghana',
    code: 'GH',
    currencyCode: 'GHS',
    phonePrefix: '233',
  },
  {
    name: 'Oman',
    code: 'OM',
    currencyCode: 'OMR',
    phonePrefix: '968',
  },
  {
    name: 'Tunisia',
    code: 'TN',
    currencyCode: 'TND',
    phonePrefix: '216',
  },
  {
    name: 'Jordan',
    code: 'JO',
    currencyCode: 'JOD',
    phonePrefix: '962',
  },
  {
    name: 'Croatia',
    code: 'HR',
    currencyCode: 'HRK',
    phonePrefix: '385',
  },
  {
    name: 'Haiti',
    code: 'HT',
    currencyCode: 'HTG',
    phonePrefix: '509',
  },
  {
    name: 'Hungary',
    code: 'HU',
    currencyCode: 'HUF',
    phonePrefix: '36',
  },
  {
    name: 'Hong Kong',
    code: 'HK',
    currencyCode: 'HKD',
    phonePrefix: '852',
  },
  {
    name: 'Honduras',
    code: 'HN',
    currencyCode: 'HNL',
    phonePrefix: '504',
  },
  {
    name: 'Venezuela',
    code: 'VE',
    currencyCode: 'VES',
    phonePrefix: '58',
  },
  {
    name: 'Puerto Rico',
    code: 'PR',
    currencyCode: 'USD',
    phonePrefix: '+1-787',
  },
  {
    name: 'Palestine',
    code: 'PS',
    currencyCode: 'ILS',
    phonePrefix: '970',
  },
  {
    name: 'Palau',
    code: 'PW',
    currencyCode: 'USD',
    phonePrefix: '680',
  },
  {
    name: 'Portugal',
    code: 'PT',
    currencyCode: 'EUR',
    phonePrefix: '351',
  },
  {
    name: 'Svalbard & Jan Mayen',
    code: 'SJ',
    currencyCode: 'NOK',
    phonePrefix: '47',
  },
  {
    name: 'Paraguay',
    code: 'PY',
    currencyCode: 'PYG',
    phonePrefix: '595',
  },
  {
    name: 'Iraq',
    code: 'IQ',
    currencyCode: 'IQD',
    phonePrefix: '964',
  },
  {
    name: 'Panama',
    code: 'PA',
    currencyCode: 'USD',
    phonePrefix: '507',
  },
  {
    name: 'French Polynesia',
    code: 'PF',
    currencyCode: 'XPF',
    phonePrefix: '689',
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    currencyCode: 'PGK',
    phonePrefix: '675',
  },
  {
    name: 'Peru',
    code: 'PE',
    currencyCode: 'PEN',
    phonePrefix: '51',
  },
  {
    name: 'Pakistan',
    code: 'PK',
    currencyCode: 'PKR',
    phonePrefix: '92',
  },
  {
    name: 'Philippines',
    code: 'PH',
    currencyCode: 'PHP',
    phonePrefix: '63',
  },
  {
    name: 'Poland',
    code: 'PL',
    currencyCode: 'PLN',
    phonePrefix: '48',
  },
  {
    name: 'St. Pierre & Miquelon',
    code: 'PM',
    currencyCode: 'EUR',
    phonePrefix: '508',
  },
  {
    name: 'Zambia',
    code: 'ZM',
    currencyCode: 'ZMW',
    phonePrefix: '260',
  },
  {
    name: 'Estonia',
    code: 'EE',
    currencyCode: 'EUR',
    phonePrefix: '372',
  },
  {
    name: 'Egypt',
    code: 'EG',
    currencyCode: 'EGP',
    phonePrefix: '20',
  },
  {
    name: 'South Africa',
    code: 'ZA',
    currencyCode: 'ZAR',
    phonePrefix: '27',
  },
  {
    name: 'Ecuador',
    code: 'EC',
    currencyCode: 'USD',
    phonePrefix: '593',
  },
  {
    name: 'Italy',
    code: 'IT',
    currencyCode: 'EUR',
    phonePrefix: '39',
  },
  {
    name: 'Vietnam',
    code: 'VN',
    currencyCode: 'VND',
    phonePrefix: '84',
  },
  {
    name: 'Solomon Islands',
    code: 'SB',
    currencyCode: 'SBD',
    phonePrefix: '677',
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    currencyCode: 'ETB',
    phonePrefix: '251',
  },
  {
    name: 'Somalia',
    code: 'SO',
    currencyCode: 'SOS',
    phonePrefix: '252',
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    currencyCode: 'USD',
    phonePrefix: '263',
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    currencyCode: 'SAR',
    phonePrefix: '966',
  },
  {
    name: 'Spain',
    code: 'ES',
    currencyCode: 'EUR',
    phonePrefix: '34',
  },
  {
    name: 'Eritrea',
    code: 'ER',
    currencyCode: 'ERN',
    phonePrefix: '291',
  },
  {
    name: 'Montenegro',
    code: 'ME',
    currencyCode: 'EUR',
    phonePrefix: '382',
  },
  {
    name: 'Moldova',
    code: 'MD',
    currencyCode: 'MDL',
    phonePrefix: '373',
  },
  {
    name: 'Madagascar',
    code: 'MG',
    currencyCode: 'MGA',
    phonePrefix: '261',
  },
  {
    name: 'St. Martin',
    code: 'MF',
    currencyCode: 'EUR',
    phonePrefix: '590',
  },
  {
    name: 'Morocco',
    code: 'MA',
    currencyCode: 'MAD',
    phonePrefix: '212',
  },
  {
    name: 'Monaco',
    code: 'MC',
    currencyCode: 'EUR',
    phonePrefix: '377',
  },
  {
    name: 'Uzbekistan',
    code: 'UZ',
    currencyCode: 'UZS',
    phonePrefix: '998',
  },
  {
    name: 'Myanmar (Burma)',
    code: 'MM',
    currencyCode: 'MMK',
    phonePrefix: '95',
  },
  {
    name: 'Mali',
    code: 'ML',
    currencyCode: 'XOF',
    phonePrefix: '223',
  },
  {
    name: 'Macau SAR China',
    code: 'MO',
    currencyCode: 'MOP',
    phonePrefix: '853',
  },
  {
    name: 'Mongolia',
    code: 'MN',
    currencyCode: 'MNT',
    phonePrefix: '976',
  },
  {
    name: 'Marshall Islands',
    code: 'MH',
    currencyCode: 'USD',
    phonePrefix: '692',
  },
  {
    name: 'Macedonia',
    code: 'MK',
    currencyCode: 'MKD',
    phonePrefix: '389',
  },
  {
    name: 'Mauritius',
    code: 'MU',
    currencyCode: 'MUR',
    phonePrefix: '230',
  },
  {
    name: 'Malta',
    code: 'MT',
    currencyCode: 'EUR',
    phonePrefix: '356',
  },
  {
    name: 'Malawi',
    code: 'MW',
    currencyCode: 'MWK',
    phonePrefix: '265',
  },
  {
    name: 'Maldives',
    code: 'MV',
    currencyCode: 'MVR',
    phonePrefix: '960',
  },
  {
    name: 'Martinique',
    code: 'MQ',
    currencyCode: 'EUR',
    phonePrefix: '596',
  },
  {
    name: 'Northern Mariana Islands',
    code: 'MP',
    currencyCode: 'USD',
    phonePrefix: '+1-670',
  },
  {
    name: 'Montserrat',
    code: 'MS',
    currencyCode: 'XCD',
    phonePrefix: '+1-664',
  },
  {
    name: 'Mauritania',
    code: 'MR',
    currencyCode: 'MRU',
    phonePrefix: '222',
  },
  {
    name: 'Isle of Man',
    code: 'IM',
    currencyCode: 'IMP',
    phonePrefix: '+44-1624',
  },
  {
    name: 'Uganda',
    code: 'UG',
    currencyCode: 'UGX',
    phonePrefix: '256',
  },
  {
    name: 'Tanzania',
    code: 'TZ',
    currencyCode: 'TZS',
    phonePrefix: '255',
  },
  {
    name: 'Malaysia',
    code: 'MY',
    currencyCode: 'MYR',
    phonePrefix: '60',
  },
  {
    name: 'Mexico',
    code: 'MX',
    currencyCode: 'MXN',
    phonePrefix: '52',
  },
  {
    name: 'Israel',
    code: 'IL',
    currencyCode: 'ILS',
    phonePrefix: '972',
  },
  {
    name: 'France',
    code: 'FR',
    currencyCode: 'EUR',
    phonePrefix: '33',
  },
  {
    name: 'St. Helena',
    code: 'SH',
    currencyCode: 'SHP',
    phonePrefix: '290',
  },
  {
    name: 'Finland',
    code: 'FI',
    currencyCode: 'EUR',
    phonePrefix: '358',
  },
  {
    name: 'Fiji',
    code: 'FJ',
    currencyCode: 'FJD',
    phonePrefix: '679',
  },
  {
    name: 'Falkland Islands',
    code: 'FK',
    currencyCode: 'FKP',
    phonePrefix: '500',
  },
  {
    name: 'Micronesia',
    code: 'FM',
    currencyCode: 'USD',
    phonePrefix: '691',
  },
  {
    name: 'Faroe Islands',
    code: 'FO',
    currencyCode: 'DKK',
    phonePrefix: '298',
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    currencyCode: 'NIO',
    phonePrefix: '505',
  },
  {
    name: 'Netherlands',
    code: 'NL',
    currencyCode: 'EUR',
    phonePrefix: '31',
  },
  {
    name: 'Norway',
    code: 'NO',
    currencyCode: 'NOK',
    phonePrefix: '47',
  },
  {
    name: 'Namibia',
    code: 'NA',
    currencyCode: 'NAD',
    phonePrefix: '264',
  },
  {
    name: 'Vanuatu',
    code: 'VU',
    currencyCode: 'VUV',
    phonePrefix: '678',
  },
  {
    name: 'New Caledonia',
    code: 'NC',
    currencyCode: 'XPF',
    phonePrefix: '687',
  },
  {
    name: 'Niger',
    code: 'NE',
    currencyCode: 'XOF',
    phonePrefix: '227',
  },
  {
    name: 'Norfolk Island',
    code: 'NF',
    currencyCode: 'AUD',
    phonePrefix: '672',
  },
  {
    name: 'Nigeria',
    code: 'NG',
    currencyCode: 'NGN',
    phonePrefix: '234',
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    currencyCode: 'NZD',
    phonePrefix: '64',
  },
  {
    name: 'Nepal',
    code: 'NP',
    currencyCode: 'NPR',
    phonePrefix: '977',
  },
  {
    name: 'Nauru',
    code: 'NR',
    currencyCode: 'AUD',
    phonePrefix: '674',
  },
  {
    name: 'Niue',
    code: 'NU',
    currencyCode: 'NZD',
    phonePrefix: '683',
  },
  {
    name: 'Cook Islands',
    code: 'CK',
    currencyCode: 'NZD',
    phonePrefix: '682',
  },
  {
    name: "Cote d'Ivoire",
    code: 'CI',
    currencyCode: 'XOF',
    phonePrefix: '225',
  },
  {
    name: 'Switzerland',
    code: 'CH',
    currencyCode: 'CHF',
    phonePrefix: '41',
  },
  {
    name: 'Colombia',
    code: 'CO',
    currencyCode: 'COP',
    phonePrefix: '57',
  },
  {
    name: 'China',
    code: 'CN',
    currencyCode: 'CNY',
    phonePrefix: '86',
  },
  {
    name: 'Cameroon',
    code: 'CM',
    currencyCode: 'XAF',
    phonePrefix: '237',
  },
  {
    name: 'Chile',
    code: 'CL',
    currencyCode: 'CLP',
    phonePrefix: '56',
  },
  {
    name: 'Cocos (Keeling) Islands',
    code: 'CC',
    currencyCode: 'AUD',
    phonePrefix: '61',
  },
  {
    name: 'Canada',
    code: 'CA',
    currencyCode: 'CAD',
    phonePrefix: '1',
  },
  {
    name: 'Congo, Republic of the',
    code: 'CG',
    currencyCode: 'XAF',
    phonePrefix: '242',
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    currencyCode: 'XAF',
    phonePrefix: '236',
  },
  {
    name: 'Congo, Democratic Republic of the',
    code: 'CD',
    currencyCode: 'CDF',
    phonePrefix: '243',
  },
  {
    name: 'Czechia',
    code: 'CZ',
    currencyCode: 'CZK',
    phonePrefix: '420',
  },
  {
    name: 'Cyprus',
    code: 'CY',
    currencyCode: 'EUR',
    phonePrefix: '357',
  },
  {
    name: 'Christmas Island',
    code: 'CX',
    currencyCode: 'AUD',
    phonePrefix: '61',
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    currencyCode: 'CRC',
    phonePrefix: '506',
  },
  {
    name: 'Curaçao',
    code: 'CW',
    currencyCode: 'ANG',
    phonePrefix: '599',
  },
  {
    name: 'Cape Verde',
    code: 'CV',
    currencyCode: 'CVE',
    phonePrefix: '238',
  },
  {
    name: 'Cuba',
    code: 'CU',
    currencyCode: 'CUP',
    phonePrefix: '53',
  },
  {
    name: 'Eswatini (Swaziland)',
    code: 'SZ',
    currencyCode: 'SZL',
    phonePrefix: '268',
  },
  {
    name: 'Syria',
    code: 'SY',
    currencyCode: 'SYP',
    phonePrefix: '963',
  },
  {
    name: 'Sint Maarten',
    code: 'SX',
    currencyCode: 'ANG',
    phonePrefix: '599',
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    currencyCode: 'KGS',
    phonePrefix: '996',
  },
  {
    name: 'Kenya',
    code: 'KE',
    currencyCode: 'KES',
    phonePrefix: '254',
  },
  {
    name: 'South Sudan',
    code: 'SS',
    currencyCode: 'SSP',
    phonePrefix: '211',
  },
  {
    name: 'Suriname',
    code: 'SR',
    currencyCode: 'SRD',
    phonePrefix: '597',
  },
  {
    name: 'Kiribati',
    code: 'KI',
    currencyCode: 'AUD',
    phonePrefix: '686',
  },
  {
    name: 'Cambodia',
    code: 'KH',
    currencyCode: 'KHR',
    phonePrefix: '855',
  },
  {
    name: 'St. Kitts & Nevis',
    code: 'KN',
    currencyCode: 'XCD',
    phonePrefix: '+1-869',
  },
  {
    name: 'Comoros',
    code: 'KM',
    currencyCode: 'KMF',
    phonePrefix: '269',
  },
  {
    name: 'Sao Tome and Principe',
    code: 'ST',
    currencyCode: 'STN',
    phonePrefix: '239',
  },
  {
    name: 'Slovakia',
    code: 'SK',
    currencyCode: 'EUR',
    phonePrefix: '421',
  },
  {
    name: 'South Korea',
    code: 'KR',
    currencyCode: 'KRW',
    phonePrefix: '82',
  },
  {
    name: 'Slovenia',
    code: 'SI',
    currencyCode: 'EUR',
    phonePrefix: '386',
  },
  {
    name: 'North Korea',
    code: 'KP',
    currencyCode: 'KPW',
    phonePrefix: '850',
  },
  {
    name: 'Kuwait',
    code: 'KW',
    currencyCode: 'KWD',
    phonePrefix: '965',
  },
  {
    name: 'Senegal',
    code: 'SN',
    currencyCode: 'XOF',
    phonePrefix: '221',
  },
  {
    name: 'San Marino',
    code: 'SM',
    currencyCode: 'EUR',
    phonePrefix: '378',
  },
  {
    name: 'Sierra Leone',
    code: 'SL',
    currencyCode: 'SLL',
    phonePrefix: '232',
  },
  {
    name: 'Seychelles',
    code: 'SC',
    currencyCode: 'SCR',
    phonePrefix: '248',
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    currencyCode: 'KZT',
    phonePrefix: '7',
  },
  {
    name: 'Cayman Islands',
    code: 'KY',
    currencyCode: 'KYD',
    phonePrefix: '+1-345',
  },
  {
    name: 'Singapore',
    code: 'SG',
    currencyCode: 'SGD',
    phonePrefix: '65',
  },
  {
    name: 'Sweden',
    code: 'SE',
    currencyCode: 'SEK',
    phonePrefix: '46',
  },
  {
    name: 'Sudan',
    code: 'SD',
    currencyCode: 'SDG',
    phonePrefix: '249',
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    currencyCode: 'DOP',
    phonePrefix: '+1-809',
  },
  {
    name: 'Dominica',
    code: 'DM',
    currencyCode: 'XCD',
    phonePrefix: '+1-767',
  },
  {
    name: 'Djibouti',
    code: 'DJ',
    currencyCode: 'DJF',
    phonePrefix: '253',
  },
  {
    name: 'Denmark',
    code: 'DK',
    currencyCode: 'DKK',
    phonePrefix: '45',
  },
  {
    name: 'British Virgin Islands',
    code: 'VG',
    currencyCode: 'USD',
    phonePrefix: '+1-284',
  },
  {
    name: 'Germany',
    code: 'DE',
    currencyCode: 'EUR',
    phonePrefix: '49',
  },
  {
    name: 'Yemen',
    code: 'YE',
    currencyCode: 'YER',
    phonePrefix: '967',
  },
  {
    name: 'Algeria',
    code: 'DZ',
    currencyCode: 'DZD',
    phonePrefix: '213',
  },
  {
    name: 'United States',
    code: 'US',
    currencyCode: 'USD',
    phonePrefix: '1',
  },
  {
    name: 'Uruguay',
    code: 'UY',
    currencyCode: 'UYU',
    phonePrefix: '598',
  },
  {
    name: 'Mayotte',
    code: 'YT',
    currencyCode: 'EUR',
    phonePrefix: '262',
  },
  {
    name: 'U.S. Outlying Islands',
    code: 'UM',
    currencyCode: 'USD',
    phonePrefix: '1',
  },
  {
    name: 'Lebanon',
    code: 'LB',
    currencyCode: 'LBP',
    phonePrefix: '961',
  },
  {
    name: 'St. Lucia',
    code: 'LC',
    currencyCode: 'XCD',
    phonePrefix: '+1-758',
  },
  {
    name: 'Laos',
    code: 'LA',
    currencyCode: 'LAK',
    phonePrefix: '856',
  },
  {
    name: 'Tuvalu',
    code: 'TV',
    currencyCode: 'AUD',
    phonePrefix: '688',
  },
  {
    name: 'Taiwan',
    code: 'TW',
    currencyCode: 'TWD',
    phonePrefix: '886',
  },
  {
    name: 'Trinidad & Tobago',
    code: 'TT',
    currencyCode: 'TTD',
    phonePrefix: '+1-868',
  },
  {
    name: 'Turkey',
    code: 'TR',
    currencyCode: 'TRY',
    phonePrefix: '90',
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    currencyCode: 'LKR',
    phonePrefix: '94',
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    currencyCode: 'CHF',
    phonePrefix: '423',
  },
  {
    name: 'Latvia',
    code: 'LV',
    currencyCode: 'EUR',
    phonePrefix: '371',
  },
  {
    name: 'Tonga',
    code: 'TO',
    currencyCode: 'TOP',
    phonePrefix: '676',
  },
  {
    name: 'Lithuania',
    code: 'LT',
    currencyCode: 'EUR',
    phonePrefix: '370',
  },
  {
    name: 'Luxembourg',
    code: 'LU',
    currencyCode: 'EUR',
    phonePrefix: '352',
  },
  {
    name: 'Liberia',
    code: 'LR',
    currencyCode: 'LRD',
    phonePrefix: '231',
  },
  {
    name: 'Lesotho',
    code: 'LS',
    currencyCode: 'LSL',
    phonePrefix: '266',
  },
  {
    name: 'Thailand',
    code: 'TH',
    currencyCode: 'THB',
    phonePrefix: '66',
  },
  {
    name: 'Togo',
    code: 'TG',
    currencyCode: 'XOF',
    phonePrefix: '228',
  },
  {
    name: 'Chad',
    code: 'TD',
    currencyCode: 'XAF',
    phonePrefix: '235',
  },
  {
    name: 'Turks & Caicos Islands',
    code: 'TC',
    currencyCode: 'USD',
    phonePrefix: '+1-649',
  },
  {
    name: 'Libya',
    code: 'LY',
    currencyCode: 'LYD',
    phonePrefix: '218',
  },
  {
    name: 'St. Vincent & Grenadines',
    code: 'VC',
    currencyCode: 'XCD',
    phonePrefix: '+1-784',
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    currencyCode: 'AED',
    phonePrefix: '971',
  },
  {
    name: 'Andorra',
    code: 'AD',
    currencyCode: 'EUR',
    phonePrefix: '376',
  },
  {
    name: 'Antigua & Barbuda',
    code: 'AG',
    currencyCode: 'XCD',
    phonePrefix: '+1-268',
  },
  {
    name: 'Afghanistan',
    code: 'AF',
    currencyCode: 'AFN',
    phonePrefix: '93',
  },
  {
    name: 'Lithuania',
    code: 'AI',
    currencyCode: 'XCD',
    phonePrefix: '+1-264',
  },
  {
    name: 'U.S. Virgin Islands',
    code: 'VI',
    currencyCode: 'USD',
    phonePrefix: '+1-340',
  },
  {
    name: 'Iceland',
    code: 'IS',
    currencyCode: 'ISK',
    phonePrefix: '354',
  },
  {
    name: 'Iran',
    code: 'IR',
    currencyCode: 'IRR',
    phonePrefix: '98',
  },
  {
    name: 'Armenia',
    code: 'AM',
    currencyCode: 'AMD',
    phonePrefix: '374',
  },
  {
    name: 'Albania',
    code: 'AL',
    currencyCode: 'ALL',
    phonePrefix: '355',
  },
  {
    name: 'Angola',
    code: 'AO',
    currencyCode: 'AOA',
    phonePrefix: '244',
  },
  {
    name: 'American Samoa',
    code: 'AS',
    currencyCode: 'USD',
    phonePrefix: '+1-684',
  },
  {
    name: 'Argentina',
    code: 'AR',
    currencyCode: 'ARS',
    phonePrefix: '54',
  },
  {
    name: 'Australia',
    code: 'AU',
    currencyCode: 'AUD',
    phonePrefix: '61',
  },
  {
    name: 'Austria',
    code: 'AT',
    currencyCode: 'EUR',
    phonePrefix: '43',
  },
  {
    name: 'Aruba',
    code: 'AW',
    currencyCode: 'AWG',
    phonePrefix: '297',
  },
  {
    name: 'India',
    code: 'IN',
    currencyCode: 'INR',
    phonePrefix: '91',
  },
  {
    name: 'Aland Islands',
    code: 'AX',
    currencyCode: 'EUR',
    phonePrefix: '+358-18',
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    currencyCode: 'AZN',
    phonePrefix: '994',
  },
  {
    name: 'Ireland',
    code: 'IE',
    currencyCode: 'EUR',
    phonePrefix: '353',
  },
  {
    name: 'Indonesia',
    code: 'ID',
    currencyCode: 'IDR',
    phonePrefix: '62',
  },
  {
    name: 'Ukraine',
    code: 'UA',
    currencyCode: 'UAH',
    phonePrefix: '380',
  },
  {
    name: 'Qatar',
    code: 'QA',
    currencyCode: 'QAR',
    phonePrefix: '974',
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    currencyCode: 'MZN',
    phonePrefix: '258',
  },
];
