import { Station } from '@dcx/ui/libs';

export const STATIONS: Station[] = [
  {
    name: '',
    code: 'VIE',
    countryCode: 'AT',
    macCode: '',
    isExternalStation: false,
    cultureCode: 'en-GB',
    timeZoneCode: 'AT',
    position: {
      latitude: '031334S',
      longitude: '0400602E',
    },
  },
  {
    name: 'Bujumbura',
    code: 'BJM',
    countryCode: 'BI',
    macCode: 'BJM',
    isExternalStation: false,
    cultureCode: 'en-GB',
    timeZoneCode: 'BI',
    position: {
      latitude: '031334S',
      longitude: '0400602E',
    },
  },
  {
    name: 'Zanzibar',
    code: 'ZNZ',
    countryCode: 'DAR',
    macCode: 'ZNZ',
    isExternalStation: false,
    cultureCode: 'en-GB',
    timeZoneCode: 'DAR',
    position: {
      latitude: '031334S',
      longitude: '0400602E',
    },
  },
  {
    name: 'Eldoret',
    code: 'EDL',
    countryCode: 'KE',
    macCode: '',
    isExternalStation: false,
    cultureCode: 'en-GB',
    timeZoneCode: 'KE',
    position: {
      latitude: '031334S',
      longitude: '0400602E',
    },
  },
  {
    name: 'Entebbe ',
    code: 'EBB',
    countryCode: 'UG',
    macCode: '',
    timeZoneCode: 'UG',
    cultureCode: 'en-US',
    isExternalStation: false,
    position: {
      latitude: '000233N',
      longitude: '0322617E',
    },
  },
  {
    name: 'Goma',
    code: 'GOM',
    countryCode: 'CG',
    macCode: 'GOM',
    isExternalStation: false,
    cultureCode: 'en-GB',
    timeZoneCode: 'CG',
    position: {
      latitude: '031334S',
      longitude: '0400602E',
    },
  },
  {
    name: 'Hahaya',
    code: 'HAH',
    countryCode: 'KM',
    macCode: '',
    timeZoneCode: 'KM',
    cultureCode: 'en-US',
    isExternalStation: false,
    position: {
      latitude: '113200S',
      longitude: '0431600E',
    },
  },
  {
    name: 'Kazán',
    code: 'KZN',
    countryCode: 'RU',
    macCode: 'KZN',
    isExternalStation: false,
    cultureCode: 'en-GB',
    timeZoneCode: 'RU',
    position: {
      latitude: '031334S',
      longitude: '0400602E',
    },
  },
  {
    name: 'Kigali International Airport',
    code: 'KGL',
    countryCode: 'RW',
    macCode: '',
    timeZoneCode: 'RW',
    cultureCode: 'en-US',
    isExternalStation: false,
    position: {
      latitude: '015804S',
      longitude: '0300824E',
    },
  },
  {
    name: 'Kisumu',
    code: 'KIS',
    countryCode: 'KE',
    macCode: 'KIS',
    isExternalStation: false,
    cultureCode: 'en-GB',
    timeZoneCode: 'KE',
    position: {
      latitude: '031334S',
      longitude: '0400602E',
    },
  },
  {
    name: 'Lamu',
    code: 'LAU',
    countryCode: 'KE',
    macCode: '',
    timeZoneCode: 'KE',
    cultureCode: 'en-US',
    isExternalStation: false,
    position: {
      latitude: '021500S',
      longitude: '0405442E',
    },
  },
  {
    name: 'Malindi',
    code: 'MYD',
    countryCode: 'KE',
    macCode: '',
    timeZoneCode: 'KE',
    cultureCode: 'en-GB',
    isExternalStation: false,
    position: {
      latitude: '031334S',
      longitude: '0400602E',
    },
  },
  {
    name: 'Mogadishu',
    code: 'MGQ',
    countryCode: 'SO',
    macCode: '',
    timeZoneCode: 'SO',
    cultureCode: 'en-US',
    isExternalStation: false,
    position: {
      latitude: '020048N',
      longitude: '0451848E',
    },
  },
  {
    name: 'Nairobi',
    code: 'NBO',
    countryCode: 'KE',
    macCode: '',
    isExternalStation: false,
    cultureCode: 'en-GB',
    timeZoneCode: 'KE',
    position: {
      latitude: '031334S',
      longitude: '0400602E',
    },
  },
  {
    name: 'Mombasa',
    code: 'MBA',
    countryCode: 'KE',
    macCode: 'MBA',
    isExternalStation: false,
    cultureCode: 'en-GB',
    timeZoneCode: 'KE',
    position: {
      latitude: '031334S',
      longitude: '0400602E',
    },
  },
];

export const STATIONS_OF_AFRICA: Station[] = [
  {
    cityCode: 'BOG',
    countryCode: 'CO',
    macCode: '',
    timeZoneCode: null!,
    cultureCode: null!,
    isExternalStation: false,
    code: 'BOG',
    name: 'Aeropuerto el dorado',
    position: {
      latitude: '3432',
      longitude: '333',
    },
  },
  {
    cityCode: 'UKA',
    countryCode: 'KE',
    macCode: '',
    timeZoneCode: null!,
    cultureCode: null!,
    isExternalStation: false,
    code: 'uka',
    name: 'ukunda',
    position: {
      latitude: '3432',
      longitude: '444',
    },
  },
  {
    cityCode: 'KIS',
    countryCode: 'KE',
    macCode: '',
    timeZoneCode: null!,
    cultureCode: null!,
    isExternalStation: false,
    code: 'KIS',
    name: 'Kisumu',
    position: {
      latitude: '3432',
      longitude: '444',
    },
  },
  {
    cityCode: 'WJR',
    countryCode: 'KE',
    macCode: '',
    timeZoneCode: null!,
    cultureCode: null!,
    isExternalStation: false,
    code: 'WJR',
    name: 'Wajir',
    position: {
      latitude: '3432',
      longitude: '444',
    },
  },
  {
    cityCode: 'ELD',
    countryCode: 'KE',
    macCode: '',
    timeZoneCode: null!,
    cultureCode: null!,
    isExternalStation: false,
    code: 'ELD',
    name: 'Eldoret',
    position: {
      latitude: '3432',
      longitude: '444',
    },
  },
  {
    cityCode: 'MBA',
    countryCode: 'KE',
    macCode: '',
    timeZoneCode: null!,
    cultureCode: null!,
    isExternalStation: false,
    code: 'MBA',
    name: 'Mombasa',
    position: {
      latitude: '3432',
      longitude: '444',
    },
  },
  {
    cityCode: 'NBO',
    countryCode: 'KE',
    macCode: '',
    timeZoneCode: null!,
    cultureCode: null!,
    isExternalStation: false,
    code: 'NBO',
    name: 'Nairobi',
    position: {
      latitude: '3432',
      longitude: '444',
    },
  },
  {
    cityCode: 'MOW',
    countryCode: 'RU',
    macCode: 'VKO',
    timeZoneCode: null!,
    cultureCode: null!,
    isExternalStation: false,
    code: 'VKO',
    name: 'Moscow (Vnukovo)',
    position: {
      latitude: '3432',
      longitude: '444',
    },
  },
  {
    cityCode: 'MOW',
    countryCode: 'RU',
    macCode: '',
    timeZoneCode: null!,
    cultureCode: null!,
    isExternalStation: false,
    code: 'SVO',
    name: 'Moscow (Saint Petersburg)',
    position: {
      latitude: '3432',
      longitude: '444',
    },
  },
];

export const MOCK_STATIONS_VM = [
  {
    code: 'NBO',
    countryCode: 'KE',
    macCode: '31',
    timeZoneCode: 'NBO',
    cultureCode: 'en-us',
    name: 'Nairobi',
    cityName: 'Nairobi',
    countryName: 'Kenya',
    cityCode: 'ANA',
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isExternalStation: false,
    isGrouped: false,
    isMac: false,
  },
  {
    code: 'MBA',
    countryCode: 'KE',
    macCode: '30',
    timeZoneCode: 'MBA',
    cultureCode: 'en-us',
    name: 'Mombasa',
    cityName: 'Mombasa',
    countryName: 'Kenya',
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isExternalStation: false,
    isGrouped: false,
    isMac: false,
  },
  {
    code: 'EDL',
    countryCode: 'KE',
    macCode: '30',
    timeZoneCode: 'EDL',
    cultureCode: 'en-us',
    name: 'Eldoret',
    cityName: 'Eldoret',
    countryName: 'Kenya',
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isExternalStation: false,
    isGrouped: false,
    isMac: false,
  },
  {
    code: 'EBB',
    countryCode: 'UG',
    macCode: '30',
    timeZoneCode: 'EBB',
    cultureCode: 'en-us',
    name: 'Entebbe',
    cityName: 'Entebbe',
    countryName: 'Kenya',
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isExternalStation: false,
    isGrouped: false,
    isMac: false,
  },
  {
    code: 'KIS',
    countryCode: 'KE',
    macCode: '30',
    timeZoneCode: 'KIS',
    cultureCode: 'en-us',
    name: 'Kisumu',
    cityName: 'Kisumu',
    countryName: 'Kenya',
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isExternalStation: false,
    isGrouped: false,
    isMac: false,
  },
  {
    code: 'MYD',
    countryCode: 'KE',
    macCode: '30',
    timeZoneCode: 'MYD',
    cultureCode: 'en-us',
    name: 'Malindi',
    cityName: 'Malindi',
    countryName: 'Kenya',
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isExternalStation: false,
    isGrouped: false,
    isMac: false,
  },
  {
    code: 'BJM',
    countryCode: 'KE',
    macCode: '30',
    timeZoneCode: 'BJM',
    cultureCode: 'en-us',
    name: 'Bujumbura International Airport',
    cityName: 'Bujumbura International Airport',
    countryName: 'Burundi',
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isExternalStation: false,
    isGrouped: false,
    isMac: false,
  },
  {
    code: 'GOM',
    countryCode: 'CO',
    macCode: '30',
    timeZoneCode: 'GOM',
    cultureCode: 'en-us',
    name: 'Goma',
    cityName: 'Gome',
    countryName: 'Congo - Brazzaville',
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isExternalStation: false,
    isGrouped: false,
    isMac: false,
  },
  {
    code: 'LAU',
    countryCode: 'KE',
    macCode: '30',
    timeZoneCode: 'LAU',
    cultureCode: 'en-us',
    name: 'Lamu',
    cityName: 'Lamu',
    countryName: 'Kenya',
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isExternalStation: false,
    isGrouped: false,
    isMac: false,
  },
  {
    code: 'SVO',
    countryCode: 'RU',
    macCode: '30',
    timeZoneCode: 'SVO',
    cultureCode: 'en-us',
    name: 'Moscow (Sheremetyevo)',
    cityName: 'Moscow (Sheremetyevo)',
    countryName: 'Russia',
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isExternalStation: false,
    isGrouped: false,
    isMac: false,
  },
  {
    cityCode: 'LIM',
    countryCode: 'PE',
    macCode: '30',
    timeZoneCode: 'MYD',
    cultureCode: 'en-us',
    isExternalStation: false,
    code: 'LIM',
    name: 'Lime',
    cityName: 'Lime',
    countryName: 'Peru',
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isGrouped: false,
    isMac: false,
  },
  {
    cityCode: 'CJA',
    countryCode: 'PE',
    macCode: '30',
    timeZoneCode: 'MYD',
    cultureCode: 'en-us',
    isExternalStation: false,
    code: 'CJA',
    name: 'Cajamarca',
    cityName: 'Cajamarca',
    countryName: 'Peru',
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isGrouped: false,
    isMac: false,
  },
  {
    cityCode: 'GIG',
    countryCode: 'BR',
    code: 'GIG',
    name: 'Aeropuerto Santos Dumont',

    cityName: 'Aeropuerto Santos Dumont',
    countryName: 'Brazil',

    macCode: '30',
    timeZoneCode: 'MYD',
    cultureCode: 'en-us',
    isExternalStation: false,
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isGrouped: false,
    isMac: false,
  },
  {
    cityCode: 'BJM',
    countryCode: 'BI',
    code: 'BJM',
    name: 'Bujumbura',

    cityName: 'Bujumbura',
    countryName: 'Burundi',

    macCode: '30',
    timeZoneCode: 'MYD',
    cultureCode: 'en-us',
    isExternalStation: false,
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isGrouped: false,
    isMac: false,
  },
  {
    cityCode: 'BEY',
    countryCode: 'LB',
    code: 'BEY',
    name: 'Beirut',

    cityName: 'Beirut',
    countryName: 'Lebanon',

    macCode: '30',
    timeZoneCode: 'MYD',
    cultureCode: 'en-us',
    isExternalStation: false,
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isGrouped: false,
    isMac: false,
  },
  {
    cityCode: 'MOW',
    countryCode: 'RU',
    code: 'BEY',
    name: 'Moscow',

    cityName: 'Moscow',
    countryName: 'Russia',

    macCode: '30',
    timeZoneCode: 'MYD',
    cultureCode: 'en-us',
    isExternalStation: false,
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isGrouped: false,
    isMac: false,
  },
  {
    cityCode: 'ZNZ',
    countryCode: 'DAR',
    code: 'ZNZ',
    name: 'Zanzibar',

    cityName: 'Zanzibar',
    countryName: 'Tanzania',

    macCode: '30',
    timeZoneCode: 'MYD',
    cultureCode: 'en-us',
    isExternalStation: false,
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isGrouped: false,
    isMac: false,
  },
  {
    cityCode: 'DAR',
    countryCode: 'DAR',
    code: 'DAR',
    name: 'Dar',

    cityName: 'Dar',
    countryName: 'Tanzania',

    macCode: '30',
    timeZoneCode: 'MYD',
    cultureCode: 'en-us',
    isExternalStation: false,
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isGrouped: false,
    isMac: false,
  },
  {
    cityCode: 'GOM',
    countryCode: 'CD',
    code: 'GOM',
    name: 'Goma',

    cityName: 'Barcelona',
    countryName: 'Spain',

    macCode: '30',
    timeZoneCode: 'MYD',
    cultureCode: 'en-us',
    isExternalStation: false,
    isSelected: false,
    position: {
      latitude: '12.3',
      longitude: '233',
    },
    isGrouped: false,
    isMac: false,
  },
];
