/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/data-not-found"

// Components
export * from './data-not-found.component';

// Models
export * from './models/data-not-found-config.model';

// Tokens
export * from './tokens/data-not-found-default-config.token';
