/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/business-common/src/lib/components/journey-status-tag"

// Components
export * from './journey-status-tag.component';
