/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/tabs"

// Components
export * from './components/tab/tab.component';
export * from './tabs.component';
export * from './components/tab-skeleton/tab-skeleton.component';

// Configs
export * from './models/tab-trigger.config';
export * from './models/tab.config';
export * from './models/tabs.config';

//Services
export * from './services/tabs.service';
