//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export enum RetrieveSegmentRequestType {
    Default = "Default",
    Search = "Search",
}

export class RetrieveSegmentManifestQuery {
    authenticationToken?: string | undefined;
    request?: RetrieveSegmentRequestDto;

    init(_data?: any) {
        if (_data) {
            this.authenticationToken = _data["authenticationToken"];
            this.request = _data["request"] ? RetrieveSegmentRequestDto.fromJS(_data["request"]) : undefined as any;
        }
    }

    static fromJS(data: any): RetrieveSegmentManifestQuery {
        data = typeof data === 'object' ? data : {};
        let result = new RetrieveSegmentManifestQuery();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["authenticationToken"] = this.authenticationToken;
        data["request"] = this.request ? this.request.toJSON() : undefined as any;
        return data;
    }
}

export class RetrieveSegmentRequestDto {
    origin?: string | undefined;
    destination?: string | undefined;
    departureDate?: Date;
    transportCarrierCode?: string | undefined;
    transportNumber?: string | undefined;
    type?: RetrieveSegmentRequestType;

    init(_data?: any) {
        if (_data) {
            this.origin = _data["origin"];
            this.destination = _data["destination"];
            this.departureDate = _data["departureDate"] ? new Date(_data["departureDate"].toString()) : undefined as any;
            this.transportCarrierCode = _data["transportCarrierCode"];
            this.transportNumber = _data["transportNumber"];
            this.type = _data["type"];
        }
    }

    static fromJS(data: any): RetrieveSegmentRequestDto {
        data = typeof data === 'object' ? data : {};
        let result = new RetrieveSegmentRequestDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["origin"] = this.origin;
        data["destination"] = this.destination;
        data["departureDate"] = this.departureDate ? this.departureDate.toISOString() : undefined as any;
        data["transportCarrierCode"] = this.transportCarrierCode;
        data["transportNumber"] = this.transportNumber;
        data["type"] = this.type;
        return data;
    }
}

export class SegmentsStatusQuery {
    authenticationToken?: string | undefined;
    requestDate?: Date | undefined;
    segmentsData?: RetrieveSegmentRequestDto[] | undefined;

    init(_data?: any) {
        if (_data) {
            this.authenticationToken = _data["authenticationToken"];
            this.requestDate = _data["requestDate"] ? new Date(_data["requestDate"].toString()) : undefined as any;
            if (Array.isArray(_data["segmentsData"])) {
                this.segmentsData = [] as any;
                for (let item of _data["segmentsData"])
                    this.segmentsData!.push(RetrieveSegmentRequestDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): SegmentsStatusQuery {
        data = typeof data === 'object' ? data : {};
        let result = new SegmentsStatusQuery();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["authenticationToken"] = this.authenticationToken;
        data["requestDate"] = this.requestDate ? this.requestDate.toISOString() : undefined as any;
        if (Array.isArray(this.segmentsData)) {
            data["segmentsData"] = [];
            for (let item of this.segmentsData)
                data["segmentsData"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}