/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/layout-swapper"

// Components
export * from './layout-swapper.component';

// Directives
export * from './directives/layout-slot.directive';
