/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/paginator"

// Components
export * from './paginator.component';

// TODO: Rename files
export * from './models/paginator.config';
