// File generated by npm run generate-barrel:component "projects/business-common/src/lib/components/boarding-pass/boarding-pass-preview"

// Components
export * from './boarding-pass-preview.component';

// Models
export * from './models/boarding-pass-segment-vm.model';
export * from './models/boarding-pass-vm.model';
