/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/date-display"

// Components
export * from './date-display.component';

// Configs
export * from './models/date-display.config';

// TODO: Rename directories
export * from './models/date-display-patterns.models';
