/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/title-heading"

// Components
export * from './title-heading.component';

// Enums
export * from './enums/title-heading.enum';

// Models
export * from './models/title-heading.model';
