/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "projects/business-common/src/lib/components/check-in-passengers-list-base"

// Components
export * from './check-in-passengers-list-base.component';
