// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/accordion"

// Components
export * from './accordion.component';
export * from './components/accordion-item/accordion-item.component';

// Configs
export * from './models/accordion.config';
