/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/icon-button"

// Components
export * from './icon-button.component';

// Models
export * from './models/icon-button.model';

// Tokens
export * from './tokens/icon-button-default-config.token';
