/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/pnr"

// Components
export * from './pnr.component';

// Models
export * from './models/pnr-config.model';
