/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/reactive-forms/src/lib/form-builder/rf-form-builder"

// Components
export * from './rf-form-builder.component';
