/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/progress-bar"

// Configs
export * from './models/progress-bar.config';

// Components
export * from './progress-bar.component';
