/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/expansion-panel"

// Components
export * from './expansion-panel.component';

// Configs
export * from './models/expansion-panel.config';

// Tokens
export * from './tokens/expansion-panel-default-config.token';
