/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/business-common/src/lib/components/passenger-types"

// Components
export * from './passenger-types.component';
