/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/business-common/src/lib/components/tier-avatar"

// Components
export * from './tier-avatar.component';

// Configs
export * from './models/tier-avatar.config';
