/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/tag"

// Components
export * from './tag.component';

// Configs
export * from './models/tag.config';
