// File generated by npm run generate-barrel:component "./projects/business-common/src/lib/components/loyalty-points"

// Components
export * from './loyalty-points.component';

// Models
export * from './models/loyalty-points.model';
