/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/badge"

// Components
export * from './badge.component';

// Configs
export * from './models/badge.config';
