/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/business-common/src/lib/components/journey-schedule"

// Components
export * from './journey-schedule.component';

// Configs
export * from './models/journey-schedule.config';
