/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/tooltip-text"

// Components
export * from './tooltip-text.component';
