/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/business-common/src/lib/components/summary-total"

// Components
export * from './summary-total.component';
