/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/tooltip"

// Components
export * from './tooltip.component';

// Tokens
export * from './tokens/tooltip-default-config.token';
