//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export class AnalyticsConfig {
    analyticsEngines?: AnalyticsEngineConfig[] | undefined;
    analyticsExceptions?: AnalyticsExceptionConfig[] | undefined;

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["analyticsEngines"])) {
                this.analyticsEngines = [] as any;
                for (let item of _data["analyticsEngines"])
                    this.analyticsEngines!.push(AnalyticsEngineConfig.fromJS(item));
            }
            if (Array.isArray(_data["analyticsExceptions"])) {
                this.analyticsExceptions = [] as any;
                for (let item of _data["analyticsExceptions"])
                    this.analyticsExceptions!.push(AnalyticsExceptionConfig.fromJS(item));
            }
        }
    }

    static fromJS(data: any): AnalyticsConfig {
        data = typeof data === 'object' ? data : {};
        let result = new AnalyticsConfig();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.analyticsEngines)) {
            data["analyticsEngines"] = [];
            for (let item of this.analyticsEngines)
                data["analyticsEngines"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.analyticsExceptions)) {
            data["analyticsExceptions"] = [];
            for (let item of this.analyticsExceptions)
                data["analyticsExceptions"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export enum AnalyticsEngine {
    GOOGLE_ANALYTICS = "GOOGLE_ANALYTICS",
    GOOGLE_TAG_MANAGER = "GOOGLE_TAG_MANAGER",
    AMPLITUDE = "AMPLITUDE",
    YANDEX_METRICA = "YANDEX_METRICA",
    ADOBE_ANALYTICS = "ADOBE_ANALYTICS",
}

export class AnalyticsEngineConfig {
    engine?: AnalyticsEngine;
    accounts?: string[] | undefined;

    init(_data?: any) {
        if (_data) {
            this.engine = _data["engine"];
            if (Array.isArray(_data["accounts"])) {
                this.accounts = [] as any;
                for (let item of _data["accounts"])
                    this.accounts!.push(item);
            }
        }
    }

    static fromJS(data: any): AnalyticsEngineConfig {
        data = typeof data === 'object' ? data : {};
        let result = new AnalyticsEngineConfig();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["engine"] = this.engine;
        if (Array.isArray(this.accounts)) {
            data["accounts"] = [];
            for (let item of this.accounts)
                data["accounts"].push(item);
        }
        return data;
    }
}

export enum AnalyticsEventType {
    Page_view = "page_view",
    Checkout = "checkout",
    Purchase = "purchase",
    Add_to_cart = "add_to_cart",
    Remove_from_cart = "remove_from_cart",
    View_item_list = "view_item_list",
    Add_payment_info = "add_payment_info",
    View_item = "view_item",
    Select_item = "select_item",
    Select_promotion = "select_promotion",
    Ibe_async = "ibe_async",
    Ibe_error = "ibe_error",
    Error_popup = "error_popup",
}

export class AnalyticsExceptionConfig {
    eventName?: AnalyticsEventType;
    analyticsEngines?: AnalyticsEngineConfig[] | undefined;
    includeDefaultEngines?: boolean | undefined;

    init(_data?: any) {
        if (_data) {
            this.eventName = _data["eventName"];
            if (Array.isArray(_data["analyticsEngines"])) {
                this.analyticsEngines = [] as any;
                for (let item of _data["analyticsEngines"])
                    this.analyticsEngines!.push(AnalyticsEngineConfig.fromJS(item));
            }
            this.includeDefaultEngines = _data["includeDefaultEngines"];
        }
    }

    static fromJS(data: any): AnalyticsExceptionConfig {
        data = typeof data === 'object' ? data : {};
        let result = new AnalyticsExceptionConfig();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["eventName"] = this.eventName;
        if (Array.isArray(this.analyticsEngines)) {
            data["analyticsEngines"] = [];
            for (let item of this.analyticsEngines)
                data["analyticsEngines"].push(item ? item.toJSON() : undefined as any);
        }
        data["includeDefaultEngines"] = this.includeDefaultEngines;
        return data;
    }
}

export class AnalyticsSettings {
    gaGtmColiving?: boolean;
    activateCustomPageViewEvent?: boolean;
    analyticsConfig?: AnalyticsConfig;

    init(_data?: any) {
        if (_data) {
            this.gaGtmColiving = _data["gaGtmColiving"];
            this.activateCustomPageViewEvent = _data["activateCustomPageViewEvent"];
            this.analyticsConfig = _data["analyticsConfig"] ? AnalyticsConfig.fromJS(_data["analyticsConfig"]) : undefined as any;
        }
    }

    static fromJS(data: any): AnalyticsSettings {
        data = typeof data === 'object' ? data : {};
        let result = new AnalyticsSettings();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["gaGtmColiving"] = this.gaGtmColiving;
        data["activateCustomPageViewEvent"] = this.activateCustomPageViewEvent;
        data["analyticsConfig"] = this.analyticsConfig ? this.analyticsConfig.toJSON() : undefined as any;
        return data;
    }
}

export class CurrencyConfig {
    symbol?: string | undefined;
    code?: string | undefined;
    name?: string | undefined;

    init(_data?: any) {
        if (_data) {
            this.symbol = _data["symbol"];
            this.code = _data["code"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): CurrencyConfig {
        data = typeof data === 'object' ? data : {};
        let result = new CurrencyConfig();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["symbol"] = this.symbol;
        data["code"] = this.code;
        data["name"] = this.name;
        return data;
    }
}

export class LoyaltyProgram {
    tierCode?: string | undefined;
    tierName?: string | undefined;
    mainColor?: string | undefined;
    darkerColor?: string | undefined;

    init(_data?: any) {
        if (_data) {
            this.tierCode = _data["tierCode"];
            this.tierName = _data["tierName"];
            this.mainColor = _data["mainColor"];
            this.darkerColor = _data["darkerColor"];
        }
    }

    static fromJS(data: any): LoyaltyProgram {
        data = typeof data === 'object' ? data : {};
        let result = new LoyaltyProgram();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["tierCode"] = this.tierCode;
        data["tierName"] = this.tierName;
        data["mainColor"] = this.mainColor;
        data["darkerColor"] = this.darkerColor;
        return data;
    }
}

export class LoyaltyPrograms {
    items?: LoyaltyProgram[] | undefined;

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(LoyaltyProgram.fromJS(item));
            }
        }
    }

    static fromJS(data: any): LoyaltyPrograms {
        data = typeof data === 'object' ? data : {};
        let result = new LoyaltyPrograms();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export class PointOfSale {
    countryCode?: string | undefined;
    stationCode?: string | undefined;
    otherCountryCodes?: string[] | undefined;
    name?: string | undefined;
    code?: string | undefined;
    isForRestOfCountries?: boolean;
    default?: boolean;
    currency?: CurrencyConfig;
    flagImageCode?: string | undefined;

    init(_data?: any) {
        if (_data) {
            this.countryCode = _data["countryCode"];
            this.stationCode = _data["stationCode"];
            if (Array.isArray(_data["otherCountryCodes"])) {
                this.otherCountryCodes = [] as any;
                for (let item of _data["otherCountryCodes"])
                    this.otherCountryCodes!.push(item);
            }
            this.name = _data["name"];
            this.code = _data["code"];
            this.isForRestOfCountries = _data["isForRestOfCountries"];
            this.default = _data["default"];
            this.currency = _data["currency"] ? CurrencyConfig.fromJS(_data["currency"]) : undefined as any;
            this.flagImageCode = _data["flagImageCode"];
        }
    }

    static fromJS(data: any): PointOfSale {
        data = typeof data === 'object' ? data : {};
        let result = new PointOfSale();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["countryCode"] = this.countryCode;
        data["stationCode"] = this.stationCode;
        if (Array.isArray(this.otherCountryCodes)) {
            data["otherCountryCodes"] = [];
            for (let item of this.otherCountryCodes)
                data["otherCountryCodes"].push(item);
        }
        data["name"] = this.name;
        data["code"] = this.code;
        data["isForRestOfCountries"] = this.isForRestOfCountries;
        data["default"] = this.default;
        data["currency"] = this.currency ? this.currency.toJSON() : undefined as any;
        data["flagImageCode"] = this.flagImageCode;
        return data;
    }
}

export class PointsOfSaleData {
    items?: PointOfSale[] | undefined;

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(PointOfSale.fromJS(item));
            }
        }
    }

    static fromJS(data: any): PointsOfSaleData {
        data = typeof data === 'object' ? data : {};
        let result = new PointsOfSaleData();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export class ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}