export enum SeatCode {
  PREMIUM = 'PREMIUM',
  PLUS = 'PLUS',
  ECONOMY = 'ECONOMY',
  EMERGENCY = 'EMERGENCY',
  FLATBED = 'FLATBED',
  BUSINESS = 'BUSINESS',
  BUSINESSCODESHARE = 'BUSINESSCODESHARE',
}
