import type { Provider } from '@angular/core';
import { BUTTON_CONFIG, DEFAULT_CONFIG_BUTTON } from '@dcx/ui/libs';

import {
  AVATAR_CONFIG,
  DEFAULT_CONFIG_AVATAR,
  DEFAULT_CONFIG_EXPANSION_PANEL,
  DEFAULT_CONFIG_ICON_BUTTON,
  DEFAULT_CONFIG_MODAL_DIALOG,
  DEFAULT_CONFIG_MODAL_FOOTER_BUTTONS,
  DEFAULT_CONFIG_PANEL,
  DEFAULT_CONFIG_POPOVER,
  DEFAULT_CONFIG_TOOLTIP,
  EXPANSION_PANEL_CONFIG,
  ICON_BUTTON_CONFIG,
  MODAL_DIALOG_CONFIG,
  MODAL_FOOTER_BUTTONS_CONFIG,
  PANEL_CONFIG,
  POPOVER_CONFIG,
  TOOLTIP_CONFIG,
} from '../../lib/components';

export const STORYBOOK_DEFAULT_CONFIG_PROVIDERS: Provider[] = [
  {
    provide: AVATAR_CONFIG,
    useValue: DEFAULT_CONFIG_AVATAR,
  },
  {
    provide: BUTTON_CONFIG,
    useValue: DEFAULT_CONFIG_BUTTON,
  },
  {
    provide: TOOLTIP_CONFIG,
    useValue: DEFAULT_CONFIG_TOOLTIP,
  },
  {
    provide: EXPANSION_PANEL_CONFIG,
    useValue: DEFAULT_CONFIG_EXPANSION_PANEL,
  },
  {
    provide: MODAL_FOOTER_BUTTONS_CONFIG,
    useValue: DEFAULT_CONFIG_MODAL_FOOTER_BUTTONS,
  },
  {
    provide: MODAL_DIALOG_CONFIG,
    useValue: DEFAULT_CONFIG_MODAL_DIALOG,
  },
  {
    provide: PANEL_CONFIG,
    useValue: DEFAULT_CONFIG_PANEL,
  },
  {
    provide: POPOVER_CONFIG,
    useValue: DEFAULT_CONFIG_POPOVER,
  },
  {
    provide: ICON_BUTTON_CONFIG,
    useValue: DEFAULT_CONFIG_ICON_BUTTON,
  },
];
