// File generated by npm run generate-barrel:component "./projects/breadcrumb/src/lib"

// Components
export * from './breadcrumb.component';

// Configs
export * from './models/breadcrumb-item.config';
export * from './models/breadcrumb.config';
