export enum EnumServiceType {
  SPORT = 'SPORT',
  BAG = 'Baggage',
  MEAL = 'Meal',
  SEAT = 'Seat',
  DUTYFREE = 'DutyFree',
  BUNDLE = 'Bundle',
  OVERSIZE = 'Oversize',
  PRIORITY = 'Priority',
  INSURANCE = 'Insurance',
  U_CONNECT = 'UConnect',
  INFANT = 'Infant',
  SPECIAL_ASSISTANCE = 'SpecialAssistance',
  BUSINESS_LOUNGE = 'BusinessLounge',
  SPECIAL_EQUIPMENT = 'SpecialEquipment',
  CHANGE_PASSENGER = 'ChangePax',
  CHANGE_FLIGHT = 'ChangeFlight',
  CANCEL_FLIGHT = 'CancelFlight',
  SMS = 'SMS',
  WHATSAPP = 'Whatsapp',
  EXTRA_SEAT = 'ExtraSeat',
  FARELOCK = 'FareLock',
  ANCILLARIES = 'Ancillaries',
  DEFAULT = 'Default',
}
