export enum ResourceType {
  STATIONS = 'stations',
  MARKETS = 'markets',
  COUNTRIES = 'countries',
  DOCUMENTS = 'documents',
  TRAVEL_DOCUMENTS = 'travelDocuments',
  ENTRANCE_DOCUMENT = 'entranceDocuments',
  BANNERS = 'banners',
  ALERTS = 'alerts',
  VISA_ZONES = 'visaZones',
  ROUTES_LOWEST_PRICE = 'routesLowestPrice',
  ALL_RESOURCES = 'allResources',
  BANNERS_DEPRECATED = 'BANNERS_DEPRECATED',
  CITIES = 'cities',
  POINTS_OF_SALE = 'pointsofSale',
  DICTIONARIES = 'dictionaries',
  ADDITIONAL_DATA = 'additionaldata',
  SERVICES = 'services',
}
