/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/remaining-time"

// Components
export * from './remaining-time.component';

// Models
export * from './models/remaining-time-config.model';
