/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/business-common/src/lib/components/points-of-sale"

// Components
export * from './points-of-sale.component';

// Models
export * from './models/points-of-sale-data.model';
