/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/toggle-masked"

// Components
export * from './toggle-masked.component';
