import { NameOrder, TextDirection } from '../core/enums';
import { UserCulture } from '../core/models';

export const USER_CULTURES: Record<string, UserCulture> = {
  en: {
    language: 'en',
    shortDateFormat: 'MM/DD/YYYY',
    longDateFormat: 'MMMM DD, YYYY',
    timeFormat: 'hh:mm A',
    is24HourClock: false,
    firstDayOfWeek: 0,
    decimalSeparator: '.',
    thousandsSeparator: ',',
    locale: 'en-US',
    region: 'US',
    nameOrder: NameOrder.FIRST_LAST,
    currency: 'USD',
    direction: TextDirection.LEFT_TO_RIGHT,
  },
  es: {
    language: 'es',
    shortDateFormat: 'DD/MM/YYYY',
    longDateFormat: 'DD [de] MMMM [de] YYYY',
    timeFormat: 'HH:mm',
    is24HourClock: true,
    firstDayOfWeek: 1,
    decimalSeparator: ',',
    thousandsSeparator: '.',
    locale: 'es-ES',
    region: 'ES',
    nameOrder: NameOrder.FIRST_LAST,
    currency: 'EUR',
    direction: TextDirection.LEFT_TO_RIGHT,
  },
  fr: {
    language: 'fr',
    shortDateFormat: 'DD/MM/YYYY',
    longDateFormat: 'DD MMMM YYYY',
    timeFormat: 'HH:mm',
    is24HourClock: true,
    firstDayOfWeek: 1,
    decimalSeparator: ',',
    thousandsSeparator: ' ',
    locale: 'fr-FR',
    region: 'FR',
    nameOrder: NameOrder.FIRST_LAST,
    currency: 'EUR',
    direction: TextDirection.LEFT_TO_RIGHT,
  },
  pt: {
    language: 'pt',
    shortDateFormat: 'DD/MM/YYYY',
    longDateFormat: 'DD [de] MMMM [de] YYYY',
    timeFormat: 'HH:mm',
    is24HourClock: true,
    firstDayOfWeek: 1,
    decimalSeparator: ',',
    thousandsSeparator: '.',
    locale: 'pt-BR',
    region: 'BR',
    nameOrder: NameOrder.FIRST_LAST,
    currency: 'EUR',
    direction: TextDirection.LEFT_TO_RIGHT,
  },
};

export const CULTURES = {
  default: 'es',
  supported: ['en', 'es', 'pt', 'fr'],
};
