/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "projects/business-common/src/lib/components/boarding-pass/boarding-pass-off-canvas"

// Components
export * from './boarding-pass-off-canvas.component';

// Models
export * from './models/boarding-pass-off-canvas-data.model';
