/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/business-common/src/lib/components/summary-price-details"

// Components
export * from './summary-price-details.component';
