/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "projects/business-common/src/lib/components/boarding-pass/add-wallet-button"

// Components
export * from './add-wallet-button.component';

// Configs
export * from './models/add-wallet-button.config';
