// File generated by npm run generate-barrel:component "./projects/mock-repository/src/lib/models/booking-fake"

// Fakes
export * from './available-fares.fake';
export * from './booking-api.fake';
export * from './booking-contact.fake';
export * from './booking-info.fake';
export * from './booking.fake';
export * from './charges.fake';
export * from './fares.fake';
export * from './journeys.fake';
export * from './legs.fake';
export * from './passenger.fake';
export * from './pricing.fake';
export * from './segments.fake';
export * from './service.fake';
export * from './transport.fake';
