/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/minus-plus"

// Components
export * from './minus-plus.component';
