export enum ProductApi {
  ACCOUNTS = 'Accounts',
  AUTHENTICATION = 'Authentication',
  AUTHORIZATION = 'Authorization',
  BOOKING = 'Booking',
  CONFIGURATION = 'Configuration',
  CONTACTS = 'Contacts',
  CUSTOMER = 'Customer',
  FINANCE = 'Finance',
  LOYALTY = 'Loyalty',
  OFFERS = 'Offers',
  PRICING = 'Pricing',
  RESOURCES = 'Resources',
  SCHEDULES = 'Schedules',
  SEGMENT_STATUS = 'SegmentStatus',
  SERVICES = 'Services',
  RULES_MANAGER = 'RulesManager',
}
