/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/description-list"

// Components
export * from './description-list.component';

// Enums
export * from './enums/description-list-layout-type.enum';
export * from './enums/description-list-option-type.enum';

// Models
export * from './models/description-list-data.model';
export * from './models/description-list-date-data.model';
export * from './models/description-list-price-data.model';
export * from './models/description-list-status-data.model';
export * from './models/description-list-text-data.model';

// Configs
export * from './models/description-list-options.config';
export * from './models/description-list.config';
