/* eslint-disable perfectionist/sort-exports */
// File generated by npm run generate-barrel:component "./projects/design-system/src/lib/components/off-canvas"

// Components
export * from './components/off-canvas-header/off-canvas-header.component';
export * from './off-canvas.component';

// Directives
export * from './directives/off-canvas-body.directive';

// Models
export * from './models/off-canvas-config.model';
